### ISSUE TITLE
$80: Tip composer should be it’s own page

### ISSUE THREAD

**Issue by kirkstrobeck** [tipfortip/issues#110]
This is an SSIM bounty, you must be an [official contributor](https://github.com/strobecksim/strobecksim.github.io/blob/master/Documents/Wiki/Index.md) to be compensated. 
<hr>

**Requirements:**

- [x] Tip composer should be it’s own page

![screen shot 2014-12-17 at 8 19 50 am](https://cloud.githubusercontent.com/assets/241963/5474365/904c8cce-85c5-11e4-9c82-5772449e6083.png)

**Comment by marshallbu** [comment]
This should be done.

**Comment by kirkstrobeck** [comment]
:+1:

**Comment by kirkstrobeck** [comment]
Only issue I see is a missing frame-level class (not sure which one) on the form view. The content areas aren’t sized per the CSS class.

**Comment by marshallbu** [comment]
main classes from modal views missing, re-added and will push up as part of #111
