### ISSUE TITLE
$80: Suggest a follower should be it’s own page

### ISSUE THREAD

**Issue by kirkstrobeck** [tipfortip/issues#111]
This is an SSIM bounty, you must be an [official contributor](https://github.com/strobecksim/strobecksim.github.io/blob/master/Documents/Wiki/Index.md) to be compensated. 
<hr>

**Requirements:**

- [ ] Suggest a follower should be it’s own page

![screen shot 2014-12-17 at 8 22 10 am](https://cloud.githubusercontent.com/assets/241963/5474400/d8241df0-85c5-11e4-8fb7-b1c97f81b0e2.png)

cc: @marshallbu

**Comment by marshallbu** [comment]
This should be done, including styling issues seen in #110
