### ISSUE TITLE
$75: Tip data in purchase response is not the same as standalone tip request

### ISSUE THREAD

**Issue by kirkstrobeck** [tipfortip/issues#119]
This is an SSIM bounty, you must be an [official contributor](https://github.com/strobecksim/strobecksim.github.io/blob/master/Documents/Wiki/Index.md) to be compensated. 
<hr>

**Requirements:**

- [ ] Get tip data in the in-app purchase response to be the same as [`/tips/{tip_id}`](http://docs.tipfortip.apiary.io/#get-%2Ftips%2F%7Btip_id%7D)

**Comment by kirkstrobeck** [comment]
@marshallbu was this fixed or non-issue?

**Comment by marshallbu** [comment]
@kirkstrobeck I think this was more a request to get updated tip.consumer data on the actual response of a successful purchase, instead of having to re-fetch the tip.  More of a "let's cut down on API requests" for efficiency rather than a blocker.

**Comment by kirkstrobeck** [comment]
You recommend a close?

**Comment by marshallbu** [comment]
Yes, I'd close this for now and worry about it when we need to do enhancements for millions of users :-D
