### ISSUE TITLE
$175: Need to take the person to their final destination

### ISSUE THREAD

**Issue by kirkstrobeck** [tipfortip/issues#120]
This is an SSIM bounty, you must be an [official contributor](https://github.com/strobecksim/strobecksim.github.io/blob/master/Documents/Wiki/Index.md) to be compensated. 
<hr>

**Background:**

I want to visit a specific tip but I’m not logged in. When I get pushed back to login it doesn’t know where I wanted to go.

**Requirements:**

- [ ] Should take you to desired destination (in this case a specific tip or place page)
- [ ] A brief comment should be added to this issue about how the data is being saved, local storage?

**Comment by marshallbu** [comment]
@kirkstrobeck created new branch `120-final-destination` on master, this should allow for following deep links if unauthorized and getting redirected after login

**Comment by kirkstrobeck** [comment]
Tested on device successfully
