### ISSUE TITLE
“Anonymous” as a protected username

### ISSUE THREAD

**Issue by kirkstrobeck** [tipfortip/issues#121]
“Anonymous” can’t be used as a username.

cc: @amoslanka

**Comment by amoslanka** [comment]
Here's the list of protected usernames. 

`anonymous tipfortip tip4tip reputation tip t4t`

If you come up with any that should be added to the list, just add them yourself (but maybe ping me too). I think thats safe enough. https://github.com/tipfortip/backend/blob/master/app/validators/protected_usernames_validator.rb#L2
