### ISSUE TITLE
Fix email links to tips

### ISSUE THREAD

**Issue by kirkstrobeck** [tipfortip/issues#125]

**Comment by kirkstrobeck** [comment]
I have made some progress on this @marshallbu -- This might be up your alley as you’re our current native expert. You can see my work on it here https://github.com/tipfortip/com.tipfortip.urltype

**Comment by kirkstrobeck** [comment]
https://documentation.appboy.com/Advanced_Use_Cases/Deep_Linking_to_In-App_Resources/iOS

**Comment by marshallbu** [comment]
http://mcgivery.com/using-custom-url-schemes-ionic-framework-app/

**Comment by kirkstrobeck** [comment]
Yes! if it also does deep linking

**Comment by kirkstrobeck** [comment]
Looks like it does support deep linking. Good find! U on this one?

**Comment by marshallbu** [comment]
Yes, even though you have to build the deep linking mechanism for it to do stuff after the launch.

**Comment by marshallbu** [comment]
Yup, this turned out to be just as much fun as I assumed.

Yet, you can now launch things via this url scheme:
`com.t4t://launch?url=path/to/thing`
example:
`com.t4t://launch?url=places/4c72849b7121a1cd52a562d1`

**Comment by marshallbu** [comment]
Tested this on emulator and device, works both with `com.t4t://` and `https://www.tipfortip.com/launch#`, should be good to go

**Comment by kirkstrobeck** [comment]
Nice! So no changes need to be made to `www`?

**Comment by marshallbu** [comment]
nope, works fine with my testing thus far

**Comment by kirkstrobeck** [comment]
BOSS
