### ISSUE TITLE
`consumer` not coming back from purchase

### ISSUE THREAD

**Issue by kirkstrobeck** [tipfortip/issues#133]
`consumer` object is not coming back from purchase. I know we discussed this, but it may have not been completed or pushed. Thoughts?

![screen shot 2014-12-24 at 12 52 30 am](https://cloud.githubusercontent.com/assets/241963/5547099/60e23bfe-8b07-11e4-9ad3-c448f1c576e8.png)

cc: @amoslanka

**Comment by marshallbu** [comment]
And are you doing this on web or on a device?

**Comment by kirkstrobeck** [comment]
Web

**Comment by marshallbu** [comment]
Okay, the in app purchase plugin doesn't work on web.  It doesn't trigger the full code loop to go through and verify/complete the purchase.  So, the tip is never really "purchased" and you wouldn't get a consumer property back on the tip, especially now that we depend on that for UI.  

Before, it was being faked, as you can see in the `iap.coffee` file on line 45.  It essentially just calls the finishorder function to complete the purchase on the UI side, but doesn't do anything useful on the backend.

**Comment by kirkstrobeck** [comment]
- [ ] So if I understand you correctly, it works on device, but not in web?
- [ ] Can we fake it in web so it shows the tip when *fake* purchased?

**Comment by marshallbu** [comment]
Correct, no in app purchasing on web, works fine on device (I just tested it both with my real FB account and a fake test user).

We could fake it on the web, but we'd have to somehow test or set a flag that it has been faked, so that we can inject the `consumer` object into the tip on each fetch, or at least on the initial fetch after it has been faked, until we leave the page.  I'd rather this be something we can turn off strictly so some enterprising soul doesn't figure out how to bypass buying tips.

**Comment by kirkstrobeck** [comment]
Right, something just for staging .. The only reason I care is for testability

**Comment by kirkstrobeck** [comment]
But this is great news, thank you for confirming !

**Comment by marshallbu** [comment]
Yes, fret not, this doing this means that @amoslanka's walled garden is working correctly, lol.

**Comment by marshallbu** [comment]
Eh, the only other problem as well is that we'll also have to stub a fake tip body as well, since the api won't give us that either if it isn't purchased.  Is that fine?

**Comment by kirkstrobeck** [comment]
I guess I see what you’re saying .. It isn’t going thru our fake app store so it would be an api hack. Maybe we can figure out a flag to throw that is on staging only to simulate a purchase that is only thrown on `www`.

**Comment by marshallbu** [comment]
Yeah, that should definitely be doable, or, if the front end detects the store doesn't exist send an extra query parameter to trigger a faked/stubbed purchase.

**Comment by kirkstrobeck** [comment]
@marshallbu is the original description of this issue resolved?

**Comment by marshallbu** [comment]
Yes, this is more of a "how do we mock IAP" on something other than a device issue.  Such as, contributing something to that Cordova Mocks extension, or asking someone at Apple why you can't do sandbox testing on an emulator.

**Comment by kirkstrobeck** [comment]
Right .. turned into a testing issue. Cool!
