### ISSUE TITLE
$50: Need to increase number of tips per place

### ISSUE THREAD

**Issue by kirkstrobeck** [tipfortip/issues#135]
This is an SSIM bounty, you must be an [official contributor](https://github.com/strobecksim/strobecksim.github.io/blob/master/Documents/Wiki/Index.md) to be compensated. 
<hr>

**Requirements:**

- [ ] Currently `/nouns/places/:place_id` only kicks back 5 tips max. It should send back at least 100 tips if not up to 1000. (Not sure what impacts the decision)

Note: Would be good to think about or get a contract in place for pagination here.

cc: @amoslanka @marshallbu

**Comment by amoslanka** [comment]
Should be done on production.

**Comment by kirkstrobeck** [comment]
How staging feels right about now
![](http://news.sciencemag.org/sites/default/files/article_images/200891711.jpg)
