### ISSUE TITLE
Profile page

### ISSUE THREAD

**Issue by kirkstrobeck** [tipfortip/issues#137]
- Name
- Username (need to be able to change username)
- Cash balance
- Reputation balance

**Comment by kirkstrobeck** [comment]
cc: @marshallbu -- poorly documented, but this is top priority

**Comment by kirkstrobeck** [comment]
@marshallbu can you confirm and close if http://localhost:8000/#/profile works with latest on `upcoming-1.1.0`?

**Comment by marshallbu** [comment]
This works for me, tested it before and again now.  Don't think I can close this though...

**Comment by kirkstrobeck** [comment]
Reputation balance is in wallet :dancers:
