### ISSUE TITLE
Transactions page

### ISSUE THREAD

**Issue by kirkstrobeck** [tipfortip/issues#138]
- Cash balance
- Reputation balance
- All transactions
  - Past tips read/purchased
  - Past tips written

**Comment by kirkstrobeck** [comment]
cc: @marshallbu -- poorly documented, but this is top priority

**Comment by kirkstrobeck** [comment]
Looking into this now

**Comment by kirkstrobeck** [comment]
Blocked by https://github.com/tipfortip/issues/issues/141

**Comment by kirkstrobeck** [comment]
@marshallbu this is prolly best next priority

**Comment by marshallbu** [comment]
Any other design for this aside from: https://github.com/tipfortip/issues/issues/2

For cash balance, is that represented accurately by the `cash` property on the user object?  For me that looks like:
```
  "cash": {
    "balance": "0.0",
    "sales_count": 0,
    "withdrawals_count": 0,
    "purchases_count": 22
  },
```

I assume transactions is only transactions that have been read/purchased, where do I get tips a user has written that haven't been read/purchased?  (feel free to call me dumb)

**Comment by kirkstrobeck** [comment]
Cash balance would be `cash.balance`

**Comment by kirkstrobeck** [comment]
> I assume transactions is only transactions that have been read/purchased

This is correct. The latter is not a part of the app yet.

**Comment by marshallbu** [comment]
Other things we'll probably need from transactions endpoint to make this more efficient:
- consumer details
- noun name

Also, do we have any test users that have actual "fake" balances?  In more depth, if they were to choose to withdraw money, where does that come from?

**Comment by kirkstrobeck** [comment]
- What are consumer details?
- Yes, not just name but full noun object

**Comment by kirkstrobeck** [comment]
@amoslanka 

- [ ] Needs purchaser object
- [ ] Needs noun object

**Comment by amoslanka** [comment]
I'm not entirely sure what specific data is needed here. On "sale" nodes what additional data is needed and on "purchase" nodes what additional data is needed?

**Comment by kirkstrobeck** [comment]
In all cases it should have both parties involved (even if listed as anonymous) and the noun in play

**Comment by amoslanka** [comment]
:ship:'ed

**Comment by kirkstrobeck** [comment]
![screen shot 2015-02-01 at 5 57 33 pm](https://cloud.githubusercontent.com/assets/241963/5994998/d0b6f624-aa3b-11e4-978c-c5aba1984742.png)
![screen shot 2015-02-01 at 5 57 43 pm](https://cloud.githubusercontent.com/assets/241963/5994999/d648548e-aa3b-11e4-90ed-0abcc2a38aeb.png)

**Comment by kirkstrobeck** [comment]
![screen shot 2015-02-01 at 7 04 55 pm](https://cloud.githubusercontent.com/assets/241963/5995335/3be4321e-aa45-11e4-85c7-b28cbc634c76.png)

**Comment by kirkstrobeck** [comment]
![screen shot 2015-02-01 at 7 05 26 pm](https://cloud.githubusercontent.com/assets/241963/5995338/4ad161d4-aa45-11e4-9777-8acad5b97c5a.png)

**Comment by amoslanka** [comment]
:clap: :clap:

**Comment by kirkstrobeck** [comment]
"Past tips written" will spin off into new page called tips or something like that.
