### ISSUE TITLE
Need to be able to get noun names from transactions endpoint

### ISSUE THREAD

**Issue by kirkstrobeck** [tipfortip/issues#143]
account/transactions

Doesn’t give me noun names, so the UI looks like this

![screen shot 2015-01-08 at 2 06 31 am](https://cloud.githubusercontent.com/assets/241963/5660968/05a2062c-96db-11e4-875c-2fd1038bc35d.png)

Also https://github.com/tipfortip/issues/issues/142

**Comment by kirkstrobeck** [comment]
cc: @amoslanka

**Comment by kirkstrobeck** [comment]
@amoslanka eta?

**Comment by amoslanka** [comment]
Shipped with https://github.com/tipfortip/backend/pull/56
