### ISSUE TITLE
Need to know how much a tip cost in reputation

### ISSUE THREAD

**Issue by kirkstrobeck** [tipfortip/issues#162]
- [ ] So that I can see how much a free tip cost me at a specific point in time I need data added to the transaction object from `~/account/transactions`

![screen shot 2015-02-01 at 5 31 36 pm](https://cloud.githubusercontent.com/assets/241963/5994853/4ae191e2-aa38-11e4-8f62-b270e7802251.png)

cc: @amoslanka

**Comment by amoslanka** [comment]
Commit tipfortip/backend@fe1cfe6 addresses this need and is shipped to production.

Please reopen if necessary.
