### ISSUE TITLE
Purchase transaction does not have a cost

### ISSUE THREAD

**Issue by kirkstrobeck** [tipfortip/issues#163]
- [ ] So that I can see how much I paid for a tip, I need to have the cost be part of the transaction object

![screen shot 2015-02-01 at 6 02 16 pm](https://cloud.githubusercontent.com/assets/241963/5995031/9aa269b4-aa3c-11e4-8557-08eaaf9d6465.png)

cc: @amoslanka

**Comment by amoslanka** [comment]
Resolved by https://github.com/tipfortip/backend/pull/56?

**Comment by kirkstrobeck** [comment]
Does it also show reputation cost?

**Comment by amoslanka** [comment]
Commit https://github.com/tipfortip/backend/commit/fe1cfe61534713ffb312dea983d0f7553bbd2f3c addresses this need and is shipped to production.

Please reopen if necessary.
