### ISSUE TITLE
Place not found 404

### ISSUE THREAD

**Issue by kirkstrobeck** [tipfortip/issues#164]
https://tipfortip-api-staging.herokuapp.com/nouns/places/5FghAFePetCuYn2Gmc1oFw

```
message: "ActiveRecord::RecordNotFound"
status: 404
```

- [ ] So that this place acts like other places, it should be available in the api

**Comment by kirkstrobeck** [comment]
cc: @amoslanka

**Comment by amoslanka** [comment]
Heyo! Whats the expectation here? There's no place in the db with id `5FghAFePetCuYn2Gmc1oFw`. So far as I can see the api is responding as expected.

**Comment by kirkstrobeck** [comment]
Hmm, well it doesn’t seem to be creating the place. I think it’s one of the first places that was created, but it didn’t get migrated properly or something. If there are any *Ardea* records maybe you could remove those so it tries to generate them again?

**Comment by amoslanka** [comment]
There's a place for the Ardea with that id on production. Is that what you're looking for?

**Comment by kirkstrobeck** [comment]
Yah, if you could delete all ardea places that would be great

**Comment by kirkstrobeck** [comment]
:rage: YAH, IF YOU COULD DELETE ALL ARDEA PLACES THAT WOULD BE GREAT! :rage:

**Comment by kirkstrobeck** [comment]
# YAH, IF YOU COULD DELETE ALL ARDEA PLACES THAT WOULD BE GREAT!

![](http://i2.kym-cdn.com/photos/images/facebook/000/000/578/1234931504682.jpg)

**Comment by amoslanka** [comment]
![](http://derp.amoslanka.com/image/0u1R083Q0w2X/Image%202015-02-04%20at%2012.26.05%20AM.png)
