### ISSUE TITLE
Convert coffee to js

### ISSUE THREAD

**Issue by kirkstrobeck** [tipfortip/issues#166]

**Comment by kirkstrobeck** [comment]
Hey @marshallbu I’ve got the master branch converted to js. We’ll want to switch to this and then make sure our upcoming branches receive the updates okay and the new changes get flowed into `js`. Could you pull this down and make sure things are working? My manual testing seems to be all good so far.

**Comment by marshallbu** [comment]
@kirkstrobeck looks fine thus far.  Are we also going to look at other ways to concat scripts and also uglify?  Just so people aren't snooping through code and getting keys.

**Comment by kirkstrobeck** [comment]
Sure, we can optimize the code some, but to assume we can abstract the keys somehow is not a viable goal with that method. There may be a cordova/phonegap plugin that gives us env variables tho, that would be reliable.

**Comment by kirkstrobeck** [comment]
:boom: POW !
