### ISSUE TITLE
Fix tips

### ISSUE THREAD

**Issue by kirkstrobeck** [tipfortip/issues#200]
It looks like that error we found the other night is still on production or potentially has some artifacts left behind.

The place at https://tipfortip-mobile.herokuapp.com/#/places/548e157d498e04514a986928 has no actual tips, but has some stray ones. I checked the db and this place was created after that meetup when we addressed the issue. Thoughts?

cc: @amoslanka

**Comment by kirkstrobeck** [comment]
This also has a compliment that isn’t showing https://api.tipfortip.com/admin/tips/1891

**Comment by amoslanka** [comment]
![](http://derp.amoslanka.com/image/1w0N3b1D2S2z/Image%202015-05-06%20at%2012.04.11%20AM.png) 

Looks correct now :+1:

**Comment by kirkstrobeck** [comment]
+1
