### ISSUE TITLE
$60: Need reputation cost of a free tip endpoint

### ISSUE THREAD

**Issue by kirkstrobeck** [tipfortip/issues#23]
This is an SSIM bounty, you must be an [official contributor](https://github.com/strobecksim/strobecksim.github.io/blob/master/Documents/Wiki/Index.md) to be compensated.
<hr>

**Requirements:**

- When I go to purchase a tip with reputation points, I need to know how much it costs.
- All reputation-only tips will cost the same amount, because it’s 1/100th of my reputation
- This may be the `current_reputation_tip_cost` value on the user object, not sure

**Notes:**

From the front-end we can do the 1/100 calculation, but this math will likely change in the future and I know we agree that the front-end should not be making a data decision.

cc: @amoslanka

**Comment by kirkstrobeck** [comment]
Yep !

**Comment by kirkstrobeck** [comment]
@amoslanka is this available?

**Comment by amoslanka** [comment]
`reputation_tip_cost` property added to the `GET /account` endpoint. 

:boom:

**Comment by amoslanka** [comment]
Reopen if you find a problem. Deployed to production and staging.
