### ISSUE TITLE
$130: “Outstanding feedback required” endpoint needed

### ISSUE THREAD

**Issue by kirkstrobeck** [tipfortip/issues#71]
This is an SSIM bounty, you must be an [official contributor](https://github.com/strobecksim/strobecksim.github.io/blob/master/Documents/Wiki/Index.md) to be compensated. 
<hr>

Prerequisites: #30 

**Requirements:**

- If a user has NOT marked a tip as helpful or not, this endpoint would return the tip id

Example:
- Request:  `GET /tip/outstanding`
- Response: *`Tip object`*

cc: @amoslanka

**Comment by amoslanka** [comment]
https://github.com/tipfortip/backend/pull/53

Currently sends responds as a collection. If you only need one, just take the first one. 

Deployed to staging 1/16/2015

/cc @kirkstrobeck

**Comment by amoslanka** [comment]
Is this feature tested and ready to ship? @kirkstrobeck

**Comment by amoslanka** [comment]
Shipped. Reopen if necessary.
